default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: is_exercise_development
  password:

test:
  <<: *default
  host: localhost
  database: is_exercise_test
  password:

production:
  <<: *default
  database: is_exercise_production
  username: cdbtjthgehckiw
  password: e401d5f4e9ec947f50d5d33de9032ce1f7f8ea475eedf36d7f3c5e9306deff2e
