default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: is_exercise_development
  password:

test:
  <<: *default
  host: localhost
  database: is_exercise_test
  password:

production:
  <<: *default
  host: ec2-54-163-234-140.compute-1.amazonaws.com
  database: d1ae6524sjou8p
  username: egcdnefsjvscdz
  password: e1021da2c70e559a1eb4f669e15dbcf736c78fa6f9e166be65b98f90835e5d28
